<?php
// $Id$

/**
 * Implementation of hook_install().
 */
function fblikebutton_install() {
//  There really is no "schema" to install.
}

/**
 * Implementation of hook_uninstall().
 */
function fblikebutton_uninstall() {
  variable_del('fblikebutton_node_types');
  variable_del('fblikebutton_show_faces');
  variable_del('fblikebutton_layout');
  variable_del('fblikebutton_color_scheme');
  variable_del('fblikebutton_action');
}
